name: CI/CD Pipeline

on:
  push:
    branches: [ develop, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Run tests
      run: npm test
    
    - name: Run linting
      run: npm run lint
    
    - name: Build project
      run: npm run build

  lighthouse:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install Lighthouse
      run: npm install -g lighthouse
    
    - name: Start server
      run: npm start &
    
    - name: Wait for server
      run: sleep 10
    
    - name: Run Lighthouse
      run: lighthouse http://localhost:8000 --output=json --output-path=./lighthouse-report.json
    
    - name: Upload Lighthouse report
      uses: actions/upload-artifact@v3
      with:
        name: lighthouse-report
        path: lighthouse-report.json

  security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Run security audit
      run: npm audit
      
    - name: Check for secrets
      uses: trufflesecurity/trufflehog@main
      with:
        path: .
        base: HEAD~1 